/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "./utils/route-matching";
export { MatchResults } from "./utils/route-matching";
export namespace Components {
    /**
     * Route component
     * Renders a component when the route matches
     */
    interface StencilRoute {
        "component"?: string;
        "componentProps"?: Record<string, any>;
        "routeRender"?: (props: { match: MatchResults }) => any;
        "url"?: string;
    }
    /**
     * Route switch component
     * Manages navigation state and passes current path to child routes
     */
    interface StencilRouteSwitch {
        /**
          * @default 0
         */
        "scrollTopOffset"?: number;
    }
    /**
     * Root router component
     * Manages routing state using hash-based navigation
     */
    interface StencilRouter {
    }
}
declare global {
    /**
     * Route component
     * Renders a component when the route matches
     */
    interface HTMLStencilRouteElement extends Components.StencilRoute, HTMLStencilElement {
    }
    var HTMLStencilRouteElement: {
        prototype: HTMLStencilRouteElement;
        new (): HTMLStencilRouteElement;
    };
    /**
     * Route switch component
     * Manages navigation state and passes current path to child routes
     */
    interface HTMLStencilRouteSwitchElement extends Components.StencilRouteSwitch, HTMLStencilElement {
    }
    var HTMLStencilRouteSwitchElement: {
        prototype: HTMLStencilRouteSwitchElement;
        new (): HTMLStencilRouteSwitchElement;
    };
    /**
     * Root router component
     * Manages routing state using hash-based navigation
     */
    interface HTMLStencilRouterElement extends Components.StencilRouter, HTMLStencilElement {
    }
    var HTMLStencilRouterElement: {
        prototype: HTMLStencilRouterElement;
        new (): HTMLStencilRouterElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-route": HTMLStencilRouteElement;
        "stencil-route-switch": HTMLStencilRouteSwitchElement;
        "stencil-router": HTMLStencilRouterElement;
    }
}
declare namespace LocalJSX {
    /**
     * Route component
     * Renders a component when the route matches
     */
    interface StencilRoute {
        "component"?: string;
        "componentProps"?: Record<string, any>;
        "routeRender"?: (props: { match: MatchResults }) => any;
        "url"?: string;
    }
    /**
     * Route switch component
     * Manages navigation state and passes current path to child routes
     */
    interface StencilRouteSwitch {
        /**
          * @default 0
         */
        "scrollTopOffset"?: number;
    }
    /**
     * Root router component
     * Manages routing state using hash-based navigation
     */
    interface StencilRouter {
    }
    interface IntrinsicElements {
        "stencil-route": StencilRoute;
        "stencil-route-switch": StencilRouteSwitch;
        "stencil-router": StencilRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Route component
             * Renders a component when the route matches
             */
            "stencil-route": LocalJSX.StencilRoute & JSXBase.HTMLAttributes<HTMLStencilRouteElement>;
            /**
             * Route switch component
             * Manages navigation state and passes current path to child routes
             */
            "stencil-route-switch": LocalJSX.StencilRouteSwitch & JSXBase.HTMLAttributes<HTMLStencilRouteSwitchElement>;
            /**
             * Root router component
             * Manages routing state using hash-based navigation
             */
            "stencil-router": LocalJSX.StencilRouter & JSXBase.HTMLAttributes<HTMLStencilRouterElement>;
        }
    }
}
